services:
  country_app:
    build:
      context: .

    ports:
      - "8000:8000"

    volumes:
      - ./CountrySeek:/CountrySeek

    env_file:
      - .env

    command: >
      sh -c "uvicorn CountrySeek.asgi:application --host 0.0.0.0 --port 8000 --reload"

    depends_on:
      - country_database
  country_database:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}